# Dashboards

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE)

library(tidyverse)
library(lubridate)
```


## Introduction
Much of the discussion up to this point has focused on traditional static. But the digital transmission of nearly all content makes it possible to provide users with an interactive experience with the data. This will allow non-technical people to interact with the data and ask question that interest them. By allowing people to interact with the data at their own pace, they gain a much deeper understanding of the relationships the graphics are trying to present.

One reason that people get more out of an interactive experience is because they just spend longer looking at the graph. Once you give somebody the option of fiddling with a slider, they spend more time processing exactly what the variable is that they are affecting. If you give them a choice of y-axis values, they'll spend longer considering each one and which one they actually want to look at.  In this sense, an interactive display forces the reader to slow down and really think about the graphic.

Second, it allows the reader to ask question that they are interested in. If I see a graph about immigration patterns in Europe, I will likely gravitate to asking about Germany, because I took German in high school and have traveled there. Whoever build the graphic couldn't have guessed why I care about Germany, but they made it possible for me to dig into the question that I care about.

## Examples:

### Covid-19 Example

This New York Times [opinion article](https://www.nytimes.com/interactive/2020/03/25/opinion/coronavirus-trump-reopen-america.html?smid=fb-share&fbclid=IwAR0FAbOYaDwLx1cm9mHNgz3VWo6T5jy77IWR_k9f-x6bv8LHd5DE3aK-438) was written to encourage readers to think about the effects of prolonged social-distancing as a mechanism for reducing the harms by this virus. It has two interactive components. The first component only has one interactive piece but it isn't too overwhelming for the reader. The article then goes on to explain different aspects of the model they built and then gives a similar interactive graphic but now have a ton of different control dials. Finally, the authors give extreme detail to their modeling process and where their data came from.

### A history of World Civilizations
[History of World Civilizations](https://public.tableau.com/en-us/gallery/history-world?tab=featured&topic=greatest-hits) gives its readers a nice clickable interface to really think about the time-line of different civilizations. History of Civilization courses typically focus on individual civilizations and don't give context to what was happening contemporaneously in, say, Chinese vs European history. This dashboard tries to address that need.

### Rainforest Biodiversity
The [Rainforest Biodiversity](https://public.tableau.com/en-us/gallery/tale-rainforest?tab=featured&topic=greatest-hits) dashboard tries to give readers an insight into just how much biodiversity exists in various 

### Oil Rigs in Texas
[Oil Rigs in Texas 2011-2016](https://public.tableau.com/en-us/gallery/texan-oil-rigs?tab=featured&topic=greatest-hits)

### Women in Politics
[Women In Politics Around the World](https://public.tableau.com/en-us/gallery/women-politics-0?tab=featured&topic=greatest-hits)

### Taxi Rides in NYC
[Taxi Rides in NYC](https://public.tableau.com/en-us/gallery/new-york-taxis?tab=featured&topic=greatest-hits)


## Deeper Thoughts

It is tempting to think of interactive graphics as either:

1. A method to get viewers to interact and therefore pay attention.
2. A shiny whiz-bang doodad that is fun to fiddle with.

But it is more subtle than that. By giving the reader some toggles to play with, we often allow them to change the level of *focus*.

Often interactive visualizations are all about changing the level of focus.

### Aggregation Level
1. Interaction is to choose the level of resolution about a certain question.
2. Typically much of the information is hidden until an aggregation level is selected. 
3. By zooming in and out of resolution, we keep the big picture in mind while allowing us to dig into as much detail as you want or need.
4. Examples
    a) [Google Maps](maps.google.com)
    b) [Google Maps Developer Documentation](https://developers.google.com/maps/documentation/maps-static/dev-guide)
    

### Highlight Level
1. Often we can show a high-level view of an entire topic. However there are too many details to be presented all at once and we want to suppress the details, but we want to see the relationship.
2. Examples
    a) [Bruce Springstein's History](http://duelingdatalarge.blogspot.com)
    b) [Game of Throne's Character Interactions](http://beta.wind-and-words.com)


### The "Me" Layer
Viewers tend to be very self-centric and a goal of most any story or analysis should be to explain how the topic affects the reader. By allowing a user to interact with and ask how does this affect:

1. Somebody like me.
2. My favorite team.
3. My state/town.
4. Examples:
    a) [NFL Elo Ratings](https://projects.fivethirtyeight.com/complete-history-of-the-nfl/)
    b) [The Birthday Problem](https://pudding.cool/2018/04/birthday-paradox/)


