# Critiques!
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE)

library(tidyverse)
library(lubridate)
```



1. 90 Years of Gender Inequality in Canadian Politics (1930-2019). 
    a) Deputies are elected members of the House of Commons.
    b) Ministers are similar to the US Cabinet members. These are senior members of the ruling party and each Minister is also a House of Commons Deputy.
    c) <iframe width="560" height="315" src="https://www.youtube.com/embed/NFLNhMsbvw4" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    d) What do the dots represent? 
        i) A person, a seat? 
        ii) Why do the dots turn black and then fall out? Why do new dots show up?
    e) What could help this video? 
        i) Are dots the right choice? 
        ii) What about a pie chart over time?
        
2. Scrollytelling! The Gates Foundations 2019 Report.
    a) https://www.gatesfoundation.org/goalkeepers/report/2019-report/#ExaminingInequality
    b) Initial graphic sets the stage, and indirectly the order of discussion. Font sets the tone that this is not data, but rather an idealized visualization.
    c) Scrollytelling is the zooming.
    d) Annotation on demand!
    
3. More Scrollytelling!  Again we are zooming out to a wider and wider perspective.
    a) https://www.nytimes.com/interactive/2019/11/06/us/politics/elizabeth-warren-policies-taxes.html
    b) The adding of dots is pretty cool.
    
3. Fonts indicating uncertainty (This is a pretty new idea!)
    a) Washington Post [article](https://www.washingtonpost.com/graphics/politics/trifecta/)
    b) Races that are considered competitive are circled in a handwriting font to indicate that the notion of "competitive" is subjective.
    c) A [journal article](https://tobias.isenberg.cc/personal/papers/Wood_2012_SRI.pdf) about "sketchiness" as a visual attribute of a graph mark.
    d) Do you think a gradient scale of sketchiness would work? Or is it a binary on/off stylistic choice?
    e) Not widely available in graphing packages.

4. Other Methods for indicating variability
    a) Background distribution. 
        i) [Flowing Data - Time Spent](https://flowingdata.com/2016/12/06/how-people-like-you-spend-their-time/)
        ii) [Flowing Data - Firsts!](https://flowingdata.com/2017/02/23/the-first-time/)
    b) Error Bars / Error Ribbons
        i) [Supreme Court Justices](https://i.redd.it/tbkdkwgxgmy31.png)
        ii) [Donald Trumps Approval Rating](https://projects.fivethirtyeight.com/trump-approval-ratings/?ex_cid=rrpromo)


## Final Projects

1. Pick a DataVis of the month from [reddit/r/dataisbeautiful](https://www.reddit.com/r/dataisbeautiful/search?q=author%3AAutoModerator+title%3A%22Battle+for+the+month+of%22&sort=new&restrict_sr=on) 
2. Pick several submissions and do a critique of them.  Pick at least one bad submission, two mediocre submissions that you can say both good and bad things about, at least one very good submission. 
3. Create a comprehensive story, creating at least 3 graphics, that a reader would be able to follow. This info-graphic should be for mass consumption among adults, so pay attention to good annotation and labeling.
4. Create a report that describes your process of and the issues that you encountered and how you overcame them, design choices you wrestled with, and revision process you used to simplify your final product.

